/* =========================================================
   0. 초기화 (개발용: 기존 테이블 및 함수 삭제)
   ========================================================= */
DROP TABLE IF EXISTS "recommendations" CASCADE;
DROP TABLE IF EXISTS "applications" CASCADE;
DROP TABLE IF EXISTS "assessment_logs" CASCADE;
DROP TABLE IF EXISTS "product_welfare_relations" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "welfare_programs" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;

/* =========================================================
   1. 공통 함수 설정 (updated_at 자동 갱신 트리거)
   ========================================================= */
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';


/* =========================================================
   2. Users 테이블
   - 사용자 및 복지 자격 정보
   ========================================================= */
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "clerk_user_id" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NULL,
    "nickname" VARCHAR(255) NULL,
    "birth_year" INTEGER NULL,
    "occupation" VARCHAR(50) NULL,
    "disability_info" JSONB NULL,
    "is_veteran" BOOLEAN DEFAULT FALSE,
    "ltc_grade" INTEGER NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_USERS" PRIMARY KEY ("id"),
    CONSTRAINT "UQ_USERS_CLERK_ID" UNIQUE ("clerk_user_id"),
    CONSTRAINT "CHK_USERS_OCCUPATION" CHECK ("occupation" IN ('student', 'worker', 'job_seeker', 'none'))
);

COMMENT ON COLUMN "users"."clerk_user_id" IS 'Clerk 인증 ID';
COMMENT ON COLUMN "users"."occupation" IS '직업 (student, worker, job_seeker, none)';
COMMENT ON COLUMN "users"."disability_info" IS '장애 정보 JSON (유형, 등급 등)';
COMMENT ON COLUMN "users"."ltc_grade" IS '장기요양등급';

/* Indexes */
CREATE INDEX "idx_users_clerk_id" ON "users" ("clerk_user_id");
CREATE INDEX "idx_users_disability_info" ON "users" USING GIN ("disability_info"); -- [GIN] 장애 정보 검색 최적화

/* Trigger */
CREATE TRIGGER update_users_modtime BEFORE UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


/* =========================================================
   3. Welfare Programs 테이블
   - 9개 부처별 보조기기 지원사업 정보 (정적 데이터)
   ========================================================= */
CREATE TABLE "welfare_programs" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ministry" VARCHAR(100) NOT NULL,
    "program_name" VARCHAR(255) NOT NULL,
    "target_criteria" JSONB NOT NULL,
    "subsidy_limit" INTEGER NULL,
    "form_template_path" VARCHAR(500) NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_WELFARE_PROGRAMS" PRIMARY KEY ("id")
);

COMMENT ON COLUMN "welfare_programs"."target_criteria" IS '자격 판별 로직 JSON';
COMMENT ON COLUMN "welfare_programs"."subsidy_limit" IS '지원 한도액';
COMMENT ON COLUMN "welfare_programs"."form_template_path" IS '신청서 템플릿 경로';

/* Indexes */
CREATE INDEX "idx_welfare_target" ON "welfare_programs" USING GIN ("target_criteria"); -- [GIN] 자격 로직 검색 최적화

/* Trigger */
CREATE TRIGGER update_welfare_modtime BEFORE UPDATE ON "welfare_programs" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


/* =========================================================
   4. Products 테이블
   - 보조기기 통합 DB
   ========================================================= */
CREATE TABLE "products" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "domain" VARCHAR(50) NULL,
    "category" VARCHAR(100) NULL,
    "market_price" INTEGER NOT NULL,
    "purchase_link" VARCHAR(2000) NULL,
    "specs" JSONB NULL,
    "tags" TEXT[] NULL,
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("id"),
    CONSTRAINT "CHK_PRODUCTS_DOMAIN" CHECK ("domain" IN ('adl', 'mobility', 'sensory', 'communication'))
);

COMMENT ON COLUMN "products"."market_price" IS '일반 시장 가격';
COMMENT ON COLUMN "products"."specs" IS '제품 스펙 JSON (무게, 크기 등)';
COMMENT ON COLUMN "products"."tags" IS 'AI 매칭용 태그 배열';
COMMENT ON COLUMN "products"."is_active" IS '활성 여부';

/* Indexes */
CREATE INDEX "idx_products_category" ON "products" ("category");
CREATE INDEX "idx_products_specs" ON "products" USING GIN ("specs"); -- [GIN] 스펙 기반 필터링 최적화
CREATE INDEX "idx_products_tags" ON "products" USING GIN ("tags");   -- [GIN] 태그 기반 검색 최적화

/* Trigger */
CREATE TRIGGER update_products_modtime BEFORE UPDATE ON "products" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


/* =========================================================
   5. Product Welfare Relations 테이블 (N:M 매핑)
   ========================================================= */
CREATE TABLE "product_welfare_relations" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "product_id" BIGINT NOT NULL,
    "program_id" BIGINT NOT NULL,
    "official_code" VARCHAR(100) NULL,
    "price_limit" INTEGER NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_PRODUCT_WELFARE_RELATIONS" PRIMARY KEY ("id"),
    CONSTRAINT "FK_REL_TO_PRODUCT" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE,
    CONSTRAINT "FK_REL_TO_PROGRAM" FOREIGN KEY ("program_id") REFERENCES "welfare_programs" ("id") ON DELETE CASCADE
);

COMMENT ON COLUMN "product_welfare_relations"."price_limit" IS '해당 사업 인정 가격';

/* Indexes */
CREATE INDEX "idx_rel_product" ON "product_welfare_relations" ("product_id");
CREATE INDEX "idx_rel_program" ON "product_welfare_relations" ("program_id");


/* =========================================================
   6. Assessment Logs 테이블
   - 진단 및 AI 분석 로그
   ========================================================= */
CREATE TABLE "assessment_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "input_data" JSONB NULL,
    "gemini_analysis" JSONB NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_ASSESSMENT_LOGS" PRIMARY KEY ("id"),
    CONSTRAINT "FK_LOGS_TO_USER" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

COMMENT ON COLUMN "assessment_logs"."gemini_analysis" IS 'AI 분석 결과 JSON';

/* Indexes */
CREATE INDEX "idx_logs_user" ON "assessment_logs" ("user_id");
CREATE INDEX "idx_logs_input" ON "assessment_logs" USING GIN ("input_data"); -- [GIN] 입력 데이터 패턴 분석용
CREATE INDEX "idx_logs_analysis" ON "assessment_logs" USING GIN ("gemini_analysis"); -- [GIN] AI 추천 결과 분석용

/* Trigger */
CREATE TRIGGER update_logs_modtime BEFORE UPDATE ON "assessment_logs" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


/* =========================================================
   7. Applications 테이블
   - 서류 자동 생성 이력
   ========================================================= */
CREATE TABLE "applications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "program_id" BIGINT NOT NULL,
    "generated_content" JSONB NULL,
    "file_url" TEXT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_APPLICATIONS" PRIMARY KEY ("id"),
    CONSTRAINT "FK_APP_TO_USER" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "FK_APP_TO_PROGRAM" FOREIGN KEY ("program_id") REFERENCES "welfare_programs" ("id") ON DELETE CASCADE
);

COMMENT ON COLUMN "applications"."file_url" IS '생성된 파일 다운로드 링크';

/* Indexes */
CREATE INDEX "idx_apps_user" ON "applications" ("user_id");
CREATE INDEX "idx_apps_content" ON "applications" USING GIN ("generated_content"); -- [GIN] 생성 내용 검색용

/* Trigger */
CREATE TRIGGER update_apps_modtime BEFORE UPDATE ON "applications" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


/* =========================================================
   8. Recommendations 테이블
   - 추천 결과 및 클릭 트래킹
   ========================================================= */
CREATE TABLE "recommendations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "log_id" UUID NOT NULL,
    "product_id" BIGINT NOT NULL,
    "is_clicked" BOOLEAN DEFAULT FALSE,
    "click_type" VARCHAR(50) DEFAULT 'general',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_RECOMMENDATIONS" PRIMARY KEY ("id"),
    CONSTRAINT "FK_RECS_TO_LOG" FOREIGN KEY ("log_id") REFERENCES "assessment_logs" ("id") ON DELETE CASCADE,
    CONSTRAINT "FK_RECS_TO_PRODUCT" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE,
    CONSTRAINT "CHK_RECS_CLICK_TYPE" CHECK ("click_type" IN ('general', 'consulting'))
);

/* Indexes */
CREATE INDEX "idx_recs_log" ON "recommendations" ("log_id");
CREATE INDEX "idx_recs_product" ON "recommendations" ("product_id");