/* =========================================================
   전체 스키마 적용 마이그레이션
   - 기존 테이블과의 호환성 유지하면서 누락된 테이블/컬럼 추가
   - 보건복지부 고시 제2023-257호 보조기기 분류체계 참고
   ========================================================= */

-- 1. 공통 함수 설정 (updated_at 자동 갱신 트리거)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 2. Users 테이블 생성/업데이트
-- 기존 users 테이블이 있는지 확인하고, 없으면 생성, 있으면 필요한 컬럼만 추가
DO $$
BEGIN
    -- users 테이블이 없으면 생성
    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'users') THEN
        CREATE TABLE "users" (
            "id" UUID NOT NULL DEFAULT gen_random_uuid(),
            "clerk_user_id" VARCHAR(255) NOT NULL,
            "email" VARCHAR(255) NULL,
            "nickname" VARCHAR(255) NULL,
            "birth_year" INTEGER NULL,
            "occupation" VARCHAR(50) NULL,
            "disability_info" JSONB NULL,
            "is_veteran" BOOLEAN DEFAULT FALSE,
            "ltc_grade" INTEGER NULL,
            "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
            "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT "PK_USERS" PRIMARY KEY ("id"),
            CONSTRAINT "UQ_USERS_CLERK_ID" UNIQUE ("clerk_user_id"),
            CONSTRAINT "CHK_USERS_OCCUPATION" CHECK ("occupation" IN ('student', 'worker', 'job_seeker', 'none'))
        );

        COMMENT ON COLUMN "users"."clerk_user_id" IS 'Clerk 인증 ID';
        COMMENT ON COLUMN "users"."occupation" IS '직업 (student, worker, job_seeker, none)';
        COMMENT ON COLUMN "users"."disability_info" IS '장애 정보 JSON (유형, 등급 등)';
        COMMENT ON COLUMN "users"."ltc_grade" IS '장기요양등급';

        CREATE INDEX "idx_users_clerk_id" ON "users" ("clerk_user_id");
        CREATE INDEX "idx_users_disability_info" ON "users" USING GIN ("disability_info");

        CREATE TRIGGER update_users_modtime BEFORE UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    ELSE
        -- 기존 테이블이 있으면 필요한 컬럼만 추가
        ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now();
        ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "birth_year" INTEGER NULL;
        ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "occupation" VARCHAR(50) NULL;
        ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "disability_info" JSONB NULL;
        ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_veteran" BOOLEAN DEFAULT FALSE;
        ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "ltc_grade" INTEGER NULL;

        -- 제약조건 추가 (없는 경우만)
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CHK_USERS_OCCUPATION') THEN
                ALTER TABLE "users" ADD CONSTRAINT "CHK_USERS_OCCUPATION" CHECK ("occupation" IN ('student', 'worker', 'job_seeker', 'none'));
            END IF;
        END $$;

        -- 인덱스 추가 (없는 경우만)
        CREATE INDEX IF NOT EXISTS "idx_users_clerk_id" ON "users" ("clerk_user_id");
        CREATE INDEX IF NOT EXISTS "idx_users_disability_info" ON "users" USING GIN ("disability_info");

        -- 트리거 추가 (없는 경우만)
        DROP TRIGGER IF EXISTS update_users_modtime ON "users";
        CREATE TRIGGER update_users_modtime BEFORE UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;

-- 3. Welfare Programs 테이블 생성
CREATE TABLE IF NOT EXISTS "welfare_programs" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ministry" VARCHAR(100) NOT NULL,
    "program_name" VARCHAR(255) NOT NULL,
    "target_criteria" JSONB NOT NULL,
    "subsidy_limit" INTEGER NULL,
    "form_template_path" VARCHAR(500) NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_WELFARE_PROGRAMS" PRIMARY KEY ("id")
);

COMMENT ON COLUMN "welfare_programs"."target_criteria" IS '자격 판별 로직 JSON';
COMMENT ON COLUMN "welfare_programs"."subsidy_limit" IS '지원 한도액';
COMMENT ON COLUMN "welfare_programs"."form_template_path" IS '신청서 템플릿 경로';

CREATE INDEX IF NOT EXISTS "idx_welfare_target" ON "welfare_programs" USING GIN ("target_criteria");

DROP TRIGGER IF EXISTS update_welfare_modtime ON "welfare_programs";
CREATE TRIGGER update_welfare_modtime BEFORE UPDATE ON "welfare_programs" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 4. Products 테이블 업데이트
-- 기존 products 테이블의 구조를 새 스키마에 맞게 업데이트
DO $$
BEGIN
    -- 컬럼명 변경: price -> market_price (데이터 보존)
    IF EXISTS (SELECT FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'price') THEN
        ALTER TABLE "products" RENAME COLUMN "price" TO "market_price";
    END IF;

    -- 새 컬럼 추가
    ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "specs" JSONB NULL;
    ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN DEFAULT TRUE;
    ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now();

    -- 컬럼 타입 변경 (NULL 허용으로 변경)
    ALTER TABLE "products" ALTER COLUMN "domain" TYPE VARCHAR(50);
    ALTER TABLE "products" ALTER COLUMN "domain" DROP NOT NULL;
    ALTER TABLE "products" ALTER COLUMN "category" TYPE VARCHAR(100);
    ALTER TABLE "products" ALTER COLUMN "category" DROP NOT NULL;
    ALTER TABLE "products" ALTER COLUMN "purchase_link" TYPE VARCHAR(2000);
    ALTER TABLE "products" ALTER COLUMN "purchase_link" DROP NOT NULL;

    -- 기존 컬럼 제거 (선택적 - 데이터 손실 가능)
    -- ALTER TABLE "products" DROP COLUMN IF EXISTS "image_url";
    -- ALTER TABLE "products" DROP COLUMN IF EXISTS "description";

    -- CHECK 제약조건 추가 (없는 경우만)
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CHK_PRODUCTS_DOMAIN') THEN
            ALTER TABLE "products" ADD CONSTRAINT "CHK_PRODUCTS_DOMAIN" CHECK ("domain" IN ('adl', 'mobility', 'sensory', 'communication'));
        END IF;
    END $$;

    -- 인덱스 추가
    CREATE INDEX IF NOT EXISTS "idx_products_category" ON "products" ("category");
    CREATE INDEX IF NOT EXISTS "idx_products_specs" ON "products" USING GIN ("specs");
    CREATE INDEX IF NOT EXISTS "idx_products_tags" ON "products" USING GIN ("tags");

    -- 트리거 추가
    DROP TRIGGER IF EXISTS update_products_modtime ON "products";
    CREATE TRIGGER update_products_modtime BEFORE UPDATE ON "products" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
END $$;

COMMENT ON COLUMN "products"."market_price" IS '일반 시장 가격';
COMMENT ON COLUMN "products"."specs" IS '제품 스펙 JSON (무게, 크기 등)';
COMMENT ON COLUMN "products"."tags" IS 'AI 매칭용 태그 배열';
COMMENT ON COLUMN "products"."is_active" IS '활성 여부';

-- 5. Product Welfare Relations 테이블 생성
CREATE TABLE IF NOT EXISTS "product_welfare_relations" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "product_id" BIGINT NOT NULL,
    "program_id" BIGINT NOT NULL,
    "official_code" VARCHAR(100) NULL,
    "price_limit" INTEGER NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_PRODUCT_WELFARE_RELATIONS" PRIMARY KEY ("id"),
    CONSTRAINT "FK_REL_TO_PRODUCT" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE,
    CONSTRAINT "FK_REL_TO_PROGRAM" FOREIGN KEY ("program_id") REFERENCES "welfare_programs" ("id") ON DELETE CASCADE
);

COMMENT ON COLUMN "product_welfare_relations"."price_limit" IS '해당 사업 인정 가격';

CREATE INDEX IF NOT EXISTS "idx_rel_product" ON "product_welfare_relations" ("product_id");
CREATE INDEX IF NOT EXISTS "idx_rel_program" ON "product_welfare_relations" ("program_id");

-- 6. Assessment Logs 테이블 업데이트
DO $$
BEGIN
    -- updated_at 컬럼 추가
    ALTER TABLE "assessment_logs" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now();

    -- user_id NOT NULL 제약조건 추가 (기존 데이터 고려)
    -- 주의: 기존에 NULL 값이 있으면 실패할 수 있음
    -- ALTER TABLE "assessment_logs" ALTER COLUMN "user_id" SET NOT NULL;

    -- 인덱스 추가
    CREATE INDEX IF NOT EXISTS "idx_logs_user" ON "assessment_logs" ("user_id");
    CREATE INDEX IF NOT EXISTS "idx_logs_input" ON "assessment_logs" USING GIN ("input_data");
    CREATE INDEX IF NOT EXISTS "idx_logs_analysis" ON "assessment_logs" USING GIN ("gemini_analysis");

    -- 트리거 추가
    DROP TRIGGER IF EXISTS update_logs_modtime ON "assessment_logs";
    CREATE TRIGGER update_logs_modtime BEFORE UPDATE ON "assessment_logs" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
END $$;

-- 7. Applications 테이블 생성
CREATE TABLE IF NOT EXISTS "applications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "program_id" BIGINT NOT NULL,
    "generated_content" JSONB NULL,
    "file_url" TEXT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT "PK_APPLICATIONS" PRIMARY KEY ("id"),
    CONSTRAINT "FK_APP_TO_USER" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
    CONSTRAINT "FK_APP_TO_PROGRAM" FOREIGN KEY ("program_id") REFERENCES "welfare_programs" ("id") ON DELETE CASCADE
);

COMMENT ON COLUMN "applications"."file_url" IS '생성된 파일 다운로드 링크';

CREATE INDEX IF NOT EXISTS "idx_apps_user" ON "applications" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_apps_content" ON "applications" USING GIN ("generated_content");

DROP TRIGGER IF EXISTS update_apps_modtime ON "applications";
CREATE TRIGGER update_apps_modtime BEFORE UPDATE ON "applications" FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 8. Recommendations 테이블 업데이트
DO $$
BEGIN
    -- click_type 컬럼 추가
    ALTER TABLE "recommendations" ADD COLUMN IF NOT EXISTS "click_type" VARCHAR(50) DEFAULT 'general';

    -- CHECK 제약조건 추가
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CHK_RECS_CLICK_TYPE') THEN
            ALTER TABLE "recommendations" ADD CONSTRAINT "CHK_RECS_CLICK_TYPE" CHECK ("click_type" IN ('general', 'consulting'));
        END IF;
    END $$;

    -- 인덱스 추가
    CREATE INDEX IF NOT EXISTS "idx_recs_log" ON "recommendations" ("log_id");
    CREATE INDEX IF NOT EXISTS "idx_recs_product" ON "recommendations" ("product_id");
END $$;

-- RLS 비활성화 (개발 단계 편의성)
ALTER TABLE IF EXISTS "users" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "welfare_programs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "products" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "product_welfare_relations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "assessment_logs" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "applications" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "recommendations" DISABLE ROW LEVEL SECURITY;

-- 권한 부여
GRANT ALL ON TABLE "users" TO anon, authenticated, service_role;
GRANT ALL ON TABLE "welfare_programs" TO anon, authenticated, service_role;
GRANT ALL ON TABLE "products" TO anon, authenticated, service_role;
GRANT ALL ON TABLE "product_welfare_relations" TO anon, authenticated, service_role;
GRANT ALL ON TABLE "assessment_logs" TO anon, authenticated, service_role;
GRANT ALL ON TABLE "applications" TO anon, authenticated, service_role;
GRANT ALL ON TABLE "recommendations" TO anon, authenticated, service_role;

