-- Products 테이블 생성
-- 보조기기 정보를 저장하는 테이블
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    domain TEXT NOT NULL, -- mobility, sensory, adl 등 대분류
    category TEXT NOT NULL, -- wheelchair, spoon 등 상세분류
    price INTEGER NOT NULL,
    image_url TEXT,
    purchase_link TEXT NOT NULL,
    tags TEXT[], -- 검색용 태그 배열 ['손떨림방지', '고대비']
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Assessment Logs 테이블 생성
-- 사용자의 평가 답변과 AI 분석 결과를 저장
CREATE TABLE IF NOT EXISTS public.assessment_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    input_data JSONB, -- 사용자 답변 (선택 영역, 증상 등)
    gemini_analysis JSONB, -- AI 분석 결과
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- Recommendations 테이블 생성
-- 평가 결과에 따른 추천 제품 목록과 클릭 여부 추적
CREATE TABLE IF NOT EXISTS public.recommendations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    log_id UUID REFERENCES public.assessment_logs(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    is_clicked BOOLEAN DEFAULT FALSE, -- 클릭 트래킹 (전환율 분석용)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- 테이블 소유자 설정
ALTER TABLE public.products OWNER TO postgres;
ALTER TABLE public.assessment_logs OWNER TO postgres;
ALTER TABLE public.recommendations OWNER TO postgres;

-- RLS (Row Level Security) 비활성화 (개발 단계 편의성)
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessment_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendations DISABLE ROW LEVEL SECURITY;

-- 권한 부여
GRANT ALL ON TABLE public.products TO anon;
GRANT ALL ON TABLE public.products TO authenticated;
GRANT ALL ON TABLE public.products TO service_role;

GRANT ALL ON TABLE public.assessment_logs TO anon;
GRANT ALL ON TABLE public.assessment_logs TO authenticated;
GRANT ALL ON TABLE public.assessment_logs TO service_role;

GRANT ALL ON TABLE public.recommendations TO anon;
GRANT ALL ON TABLE public.recommendations TO authenticated;
GRANT ALL ON TABLE public.recommendations TO service_role;

